import{a as y,S as p,i}from"./assets/vendor-BfjKTZs6.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const s of e)if(s.type==="childList")for(const f of s.addedNodes)f.tagName==="LINK"&&f.rel==="modulepreload"&&n(f)}).observe(document,{childList:!0,subtree:!0});function r(e){const s={};return e.integrity&&(s.integrity=e.integrity),e.referrerPolicy&&(s.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?s.credentials="include":e.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function n(e){if(e.ep)return;e.ep=!0;const s=r(e);fetch(e.href,s)}})();function g(o){const r="https://pixabay.com/api/?key="+"49486795-430aa06a6e639b9f88254bdb1"+"&q="+encodeURIComponent(o)+"&image_type=photo&orientation=horizontal&safesearch=true";return y.get(r).then(n=>[...n.data.hits])}const L=new p(".gallery a",{captionsData:"alt",captionDelay:250});function h(o,t=!1){const r=document.querySelector(".gallery");t&&(r.innerHTML="");const n=o.map(e=>`
      <li class="gallery-item">
        <a href="${e.largeImageURL}">
          <img src="${e.webformatURL}" alt="${e.tags}" width="360" height="200">
        </a>
        <div class="image-info">
          <p><strong>Likes:</strong> ${e.likes}</p>
          <p><strong>Views:</strong> ${e.views}</p>
          <p><strong>Comments:</strong> ${e.comments}</p>
          <p><strong>Downloads:</strong> ${e.downloads}</p>
        </div>
      </li>`).join("");r.insertAdjacentHTML("beforeend",n),L.refresh()}i.settings({position:"topRight",iconColor:"#fff",messageColor:"#fff"});const l=document.querySelector(".gallery"),a=document.querySelector(".form"),c=document.querySelector(".load-more");let d=1,m="";a.addEventListener("submit",b);c.addEventListener("click",w);async function b(o){o.preventDefault();const t=a.elements["search-text"].value.trim();if(!t){i.warning({message:"Please enter a search query!"});return}l.innerHTML="",m=t,d=1,c.classList.add("hidden"),u(!0);try{const r=await g(m,d);if(r.length===0)throw new Error("Sorry, no images found. Please try again!");h(r,l),c.classList.remove("hidden")}catch(r){i.error({message:r.message})}finally{u(!1)}}async function w(){var o;d+=1,u(!0);try{const t=await g(m,d);if(t.length===0){i.info({message:"We're sorry, but you've reached the end of search results."}),c.classList.add("hidden");return}h(t,l);const r=((o=l.firstElementChild)==null?void 0:o.getBoundingClientRect().height)||0;window.scrollBy({top:r*2,behavior:"smooth"})}catch(t){i.error({message:t.message})}finally{u(!1)}}function u(o){const t=document.querySelector(".loader");o?(t.classList.remove("hidden"),a.elements["search-text"].setAttribute("readonly",!0),a.elements["search-button"].disabled=!0):(t.classList.add("hidden"),a.elements["search-text"].removeAttribute("readonly"),a.elements["search-button"].disabled=!1)}
//# sourceMappingURL=index.js.map
