import{a as y,S as p,i}from"./assets/vendor-BfjKTZs6.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))o(t);new MutationObserver(t=>{for(const n of t)if(n.type==="childList")for(const f of n.addedNodes)f.tagName==="LINK"&&f.rel==="modulepreload"&&o(f)}).observe(document,{childList:!0,subtree:!0});function r(t){const n={};return t.integrity&&(n.integrity=t.integrity),t.referrerPolicy&&(n.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?n.credentials="include":t.crossOrigin==="anonymous"?n.credentials="omit":n.credentials="same-origin",n}function o(t){if(t.ep)return;t.ep=!0;const n=r(t);fetch(t.href,n)}})();function g(s){const r="https://pixabay.com/api/?key="+"49486795-430aa06a6e639b9f88254bdb1"+"&q="+encodeURIComponent(s)+"&image_type=photo&orientation=horizontal&safesearch=true";return y.get(r).then(o=>[...o.data.hits])}const L=new p(".gallery a",{captionsData:"alt",captionDelay:250});function h(s){const e=document.querySelector(".gallery");e.innerHTML="";const r=s.map(o=>`
      <li class="gallery-item">
        <a href="${o.largeImageURL}">
          <img src="${o.webformatURL}" alt="${o.tags}" width="360" height="200">
        </a>
        <div class="image-info">
          <p><strong>Likes:</strong> ${o.likes}</p>
          <p><strong>Views:</strong> ${o.views}</p>
          <p><strong>Comments:</strong> ${o.comments}</p>
          <p><strong>Downloads:</strong> ${o.downloads}</p>
        </div>
      </li>`).join("");e.insertAdjacentHTML("beforeend",r),L.refresh()}i.settings({position:"topRight",iconColor:"#fff",messageColor:"#fff"});const l=document.querySelector(".gallery"),a=document.querySelector(".form"),c=document.querySelector(".load-more");let d=1,m="";a.addEventListener("submit",b);c.addEventListener("click",w);async function b(s){s.preventDefault();const e=a.elements["search-text"].value.trim();if(!e){i.warning({message:"Please enter a search query!"});return}l.innerHTML="",m=e,d=1,c.classList.add("hidden"),u(!0);try{const r=await g(m,d);if(r.length===0)throw new Error("Sorry, no images found. Please try again!");h(r,l),c.classList.remove("hidden")}catch(r){i.error({message:r.message})}finally{u(!1)}}async function w(){var s;d+=1,u(!0);try{const e=await g(m,d);if(e.length===0){i.info({message:"We're sorry, but you've reached the end of search results."}),c.classList.add("hidden");return}h(e,l);const r=((s=l.firstElementChild)==null?void 0:s.getBoundingClientRect().height)||0;window.scrollBy({top:r*2,behavior:"smooth"})}catch(e){i.error({message:e.message})}finally{u(!1)}}function u(s){const e=document.querySelector(".loader");s?(e.classList.remove("hidden"),a.elements["search-text"].setAttribute("readonly",!0),a.elements["search-button"].disabled=!0):(e.classList.add("hidden"),a.elements["search-text"].removeAttribute("readonly"),a.elements["search-button"].disabled=!1)}
//# sourceMappingURL=index.js.map
